### ISSUE TITLE
View transition - Diagonal mystic 

### ISSUE THREAD

**Issue by Anna-Kyra** [fdnd-agency/visual-thinking#235]
# Diagonal mystic view transition
![Image](https://github.com/user-attachments/assets/9c4461ac-5429-49d4-8a6e-0ed2af4f5705)

Branch:
Website link: https://6762e8c47ef70e00bfeeffe7--visual-thinking-view-transition-ak.netlify.app/

### Links
- Diagonal motion blur - code pen: https://codepen.io/flyorboom/pen/jOELoqM
- Daniel Schults - batman viewtransition (geen scale, maar perspective): https://iamschulz.com/view-transition-api/
- Animation met mask: https://www.smashingmagazine.com/2023/09/revealing-images-css-mask-animations/
- Transition met masks: https://tympanus.net/codrops/2016/09/29/transition-effect-with-css-masks/

### Tutorials:
- google for developers - viewtransitions: https://www.youtube.com/watch?v=oXSFwix7eR8
```
  item.parentNode.style.viewTransitionName ='--product-' +i
```

### Moodboard
![Image](https://github.com/user-attachments/assets/60838532-8adb-4367-a60e-d24233c4b124)

> Link naar [pinterest board](https://nl.pinterest.com/cuinera5/diagonal-mystic/)

## Code pen probeersels:
- View transition oefening Krijn: https://codepen.io/sad-Panda-the-flexboxer/pen/EaYyaop
- View transition, scale: https://codepen.io/the_legends_of_panda/pen/mybEeyp?editors=0110
- > scale werkt niet (want screenshots en pixels) moet dit doen met css perspective/3d, [daniel schults batman voorbeeld](https://iamschulz.com/view-transition-api/)
- Svg animatie: https://codepen.io/the_legends_of_panda/pen/WbeobBw 
- - Werkte niet echt, responsive doet raar (heeft waarschijnlijk met de JS te maken)

### Groffe schets
![Image](https://github.com/user-attachments/assets/622681ce-b336-4ccd-8b0b-bea2ef0bcfe2)

Wil eerst links proberen, daarna vormen in een soort ster/meteator met sterretjes er omheen. 
> de eerste heb ik uiteindelijk gemaakt zie [branche](https://github.com/fdnd-agency/visual-thinking/tree/anna-kyra-view-transition)

#### Meer animatie schetsen (niet gebruikt)
![Image](https://github.com/user-attachments/assets/d3b7e66a-4abd-4de0-a3bf-0045f2037f17)

![Image](https://github.com/user-attachments/assets/f0621c39-55be-4c04-8ef6-5d3ed935c2ab)

## Probeersels
https://github.com/user-attachments/assets/8332b080-843f-4e24-af82-8176d803566f
- Is met [svg gator](https://www.svgator.com/) geanimeerd
- Wilde dit als page transition gebruik voor het wat mystical gevoel (wilde het meer mystical maken, maar was er niet aan toe gekomen :( )
- Had het in een [codepen ](https://codepen.io/the_legends_of_panda/pen/WbeobBw)gedropt om het als page transitition/animatie te proberen, maar ik kreeg de responsiveheid maar niet goed (komt waarschijnlijk doordat de js de path en translate overschrijft) 
- Wilde het in een andere [branch](https://github.com/fdnd-agency/visual-thinking/tree/anna-kyra-view-transition02) proberen om het als `background-image` te gebruiken en dan goed positioneren, maar blijkbaar werken scripts niet als je dit doet?
- 
## Code

```CSS
@view-transition {
  navigation: auto;
}
@media (prefers-reduced-motion: no-preference) { 
  @keyframes fade-in {
    0% {
      transform: translate(0%, 0%);
    }

    99% {
      transform: translate(0%, 0%);
    }

    100% {
      transform: translate(100%, 100%);
    }
  }

  @keyframes fade-out {
    0% {
      transform: translate(-100%, 0%);
    }

    99% {
      transform: translate(-100%, 0%);
    }

    100% {
      transform: translate(0%, 0%);
    }
  }

  ::view-transition-old(root) {
    animation: fade-in 1.5s;
  }

  ::view-transition-new(root) {
    animation: fade-out 1.5s;
  }

  /* .methods-focus-state {
    view-transition-name: wopp;
  } */

  @keyframes skew {
    0% {
        transform: translate(-100%, -100%) rotate(45deg) skew(0deg) scale3d(0,0,0);
    }
    
    10% {
        transform: translate(-50%, -50%) scale3d(0,0,0) rotate(45deg) skew(45deg) ;
    }
    
    40% {
        transform: translate(0%, 0%) scale3d(1,1,1) rotate(0deg) skew(0deg)  ;
    }
    
    60% {
        transform: translate(0%, 0%) scale3d(1,1,1) rotate(0deg) skew(0deg)  ;
    }
    90% {
        transform: translate(0%, 0%) scale3d(0,0,0) rotate(45deg) skew(45deg) ;
    }
    100% {
        transform: translate(0%, 0%) rotate(135deg) skew(0deg) scale3d(0,0,0);
    }
  }

  ::view-transition-group(page-transition) {
    animation: skew 3s cubic-bezier(.99,0,0,.99);
    transition: all 0s;
  }
}
```
