### ISSUE TITLE
Scroll animation - Liquid acid graphic

### ISSUE THREAD

**Issue by Anna-Kyra** [fdnd-agency/visual-thinking#236]
# Liquid acid graphic scroll animation
![Image](https://github.com/user-attachments/assets/135952ed-a1f7-4146-85cd-0ecd2468f14e)

Branch link: [Visual Thinking - Anna-Kyra](https://github.com/Anna-Kyra/visual-thinking/tree/anna-kyra-scroll-animation)
> In de +layoute.svelte staat alle veranderingen

> Heb hem bij de scroll animations nog even geforked, omdat ik nog geen access had bij de fdnd-agency en ik snel wilde beginnen

Website link: https://visual-thinking-scroll-animation-ak.netlify.app/tekenmethodes

### Links
- Svg filter, liquid scroll: https://codepen.io/fand/pen/XWebowa?editors=1100

- Liquidy met shaders voorbeeld: http://robinmastromarino.com/project/fanny-myard
- Gradient shaders tutorial: https://www.youtube.com/watch?v=ceJ82RaW9mM
- Shaders inspiration: https://innovations.vareximaging.com/
> Had veel inspiratie die shaders haddden, wilde eigenlijk gewoon shaders leren. Ben nu door cyd de Three.js Journey course aan het doen van Bruno Simon. Link naar repo: [Three.js Lessons - Anna-Kyra](https://github.com/Anna-Kyra/three.js-lessons)

### Moodboard
![Image](https://github.com/user-attachments/assets/c8cf19d3-3677-4376-9277-3c12875cfad8)
> Link naar [pinterest board](https://nl.pinterest.com/cuinera5/liquid-acid/)

### Video
https://github.com/user-attachments/assets/1adcd155-b72f-43f7-a0a0-83667c2ae0f4

Heb veel met svg filters geknoeid, de performance is **supper** slecht daardoor geworden
> Wilde nog een matrix reference maken met een menu waarbij je of de redpill (normaal) of de blue pill (scroll animation) moest kiezen, maar had daar niet genoeg tijd voor gehad...en het lukte ff niet haha

### Code

Zie de code in deze branch: Branch link: [Visual Thinking - Anna-Kyra](https://github.com/Anna-Kyra/visual-thinking/tree/anna-kyra-scroll-animation)

In de +layoute.svelte:
> SVG filter

```HTML
<svg  width="0" height="0" viewBox="0 0 1728 852" fill="none" preserveAspectRatio="xMidYMin slice">
    <defs>
        <filter id="noise">
            <feTurbulence  type="fractalNoise" id="turbulence" baseFrequency="{x}" numOctaves="1" result="noise" seed="0"/>
            <feDisplacementMap id="displacement" in="SourceGraphic" in2="noise" scale="300" />
        </filter>
        <filter id="noise-background">
            <feTurbulence  type="fractalNoise" id="turbulence" baseFrequency="0.0" numOctaves="2" result="noise" seed="0"/>
            <feDisplacementMap id="displacement" in="SourceGraphic" in2="noise" scale="300" />
        </filter>
    </defs>
</svg>
```

Svg scroll transition:

> JS

```JS
    import { onMount } from 'svelte';
    import Header from "$lib/molecules/header.svelte";
    import Footer from "$lib/molecules/footer.svelte";

    let documentHeight;
    
    onMount(() => {
        documentHeight = document.documentElement.scrollHeight;
        console.log('De totale documenthoogte is:', documentHeight);


        window.addEventListener('scroll', () => {
            document.body.style.setProperty('--scroll',window.pageYOffset / (document.body.offsetHeight - window.innerHeight));
        }, false);


    });


    export let x = 0.0;
    export let a = 1;


    let box;
    
    function scrollOffset(){
        let scrollTop = box.scrollTop
        let boxHeight = box.clientHeight


        console.log('scrolltop:' + scrollTop)


        console.log(documentHeight)


        x = 0.000001 * box.scrollTop
        // boxHeight = box.clientHeight


        a = 0.1 * box.scrollTop


        if(x > 0.003) {
            x = 0.003
        }
    }
```

```HTML
    <div bind:this={box} on:scroll={scrollOffset} class="liquid-acid-theme">
        <slot/>
    </div>
```

CSS:

> Scroll animation

 ```CSS
@supports (animation-timeline: view()) {
        @media (prefers-reduced-motion: no-preference) { 
            .liquid-acid-theme {
                margin: 0;
                left: 0;
                filter: url('#noise');
                position: absolute;
                width: 100%;
                height: 100%;
                overflow-y: auto;
                /* filter: blur(calc(10px * var(--x))); */
                /* background-color: blue; */


                scroll-timeline: --squareTimeline y;
                scroll-timeline: --squareTimeline vertical;
                animation-name: rotateAnimation, draaien;
                animation-duration: 1ms;
                animation-timing-function: ease-out;
                animation-timeline: --squareTimeline;  
            }


            @keyframes rotateAnimation {
                0% {
                    --angle:0deg; 
                    transform: rotate(0deg);
                    background-color: white;
                    scale: 1;
                    transform-origin: center;
                }


                50% {
                    transform: rotate(40deg) ;
                }


                60% {
                    transform: rotate(-40deg);
                }


                100% {
                    --angle:360deg;
                    transform: rotate(0deg);
                    /* background-color: black; */
                    background-color: white;
                    scale: 0.1;
                    
                }


            }
        }
    }
```

> Wrapper

```CSS
    .wrapper {
        width: 100%;
        height: calc(100vh - 104.5px);
        animation: draaien 10s infinite linear;


        scroll-timeline: scrollTimeline vertical;
        animation: draaien 10s linear infinite;


        @supports (animation-timeline: view()) {
            @media (prefers-reduced-motion: no-preference) { 
                background-color: black;
                background: 
                radial-gradient(circle at 50% 55%, rgba(0,0,0,1) 8%, rgba(0,0,0,0) 100%),
                repeating-conic-gradient(
                    from var(--angle, 0deg) at 50% 55%, 					 
                    orange 0deg,
                    dodgerblue,
                    deeppink,
                    orange 60deg
                );
                background-size: cover, cover;
                background-position: center, center;
                box-shadow: inset 0px 0px 1000px 100px #000;
            }
        }
    }
```

## Code review
- Krijn: Kijk naar path-draw animatie/vector animatie. Das beter voor/in de stijl van de opdracht gever. 
> Kijk naar: https://jakearchibald.com/2013/animated-line-drawing-svg/
- `animation(root)` gebruiken om de achtergrond ook mee te laten scrollen
